<?php

namespace TDevAgency\LaravelStubsReturnDeclaration;

class Patches extends \cweagans\Composer\Patches
{
    protected function getAndApplyPatch(
        \Composer\Util\RemoteFilesystem $downloader,
        $install_path,
        $patch_url,
        \Composer\Package\PackageInterface $package
    ) {
        $patch_url = __DIR__ . '/../' . $patch_url;
        parent::getAndApplyPatch(
            $downloader,
            $install_path,
            $patch_url,
            $package
        ); // TODO: Change the autogenerated stub
    }

}
